Forgot to bump msgpack to 1.7.2 when not local. There's a pointer error on mac
```shell
current directory: /Users/julien/Software/Others/openstudio_gems/openstudio-gems/.bundle/ruby/3.2.0/gems/msgpack-1.4.2/ext/msgpack
make DESTDIR\= sitearchdir\=./.gem.20240417-54838-gkipa7 sitelibdir\=./.gem.20240417-54838-gkipa7 clean

current directory: /Users/julien/Software/Others/openstudio_gems/openstudio-gems/.bundle/ruby/3.2.0/gems/msgpack-1.4.2/ext/msgpack
make DESTDIR\= sitearchdir\=./.gem.20240417-54838-gkipa7 sitelibdir\=./.gem.20240417-54838-gkipa7
compiling buffer.c
compiling buffer_class.c
buffer_class.c:261:17: error: incompatible function pointer types passing 'VALUE (VALUE)' (aka 'unsigned long (unsigned long)') to parameter of type 'VALUE (*)(VALUE,
VALUE)' (aka 'unsigned long (*)(unsigned long, unsigned long)') [-Wincompatible-function-pointer-types]
                read_until_eof_error, (VALUE)(void*) args,
                ^~~~~~~~~~~~~~~~~~~~
/Users/julien/.rvm/rubies/ruby-3.2.2/include/ruby-3.2.0/ruby/internal/iterator.h:388:63: note: passing argument to parameter 'r_proc' here
VALUE rb_rescue2(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*r_proc)(VALUE, VALUE), VALUE data2, ...);
                                                              ^
1 error generated.
make: *** [buffer_class.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/julien/Software/Others/openstudio_gems/openstudio-gems/.bundle/ruby/3.2.0/gems/msgpack-1.4.2 for inspection.
Results logged to /Users/julien/Software/Others/openstudio_gems/openstudio-gems/.bundle/ruby/3.2.0/extensions/arm64-darwin-23/3.2.0/msgpack-1.4.2/gem_make.out
```